services:
  yolo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo_detector
    restart: unless-stopped
    ports:
      # to port 5000 inside this container.
      - "5000:5000"
      
    stdin_open: true  # Keep stdin open for an interactive shell
    tty: true         # Allocate a pseudo-TTY
    
    command: |
      /bin/bash -c "trap : TERM INT; sleep infinity & wait"
